name: Update analysis
on:
  workflow_dispatch:
  schedule:
    # Run weekly
    - cron: "0 0 * * 0"
jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Robot Version
        run: robot --version
      - name: Install dependencies
        run: |
          python -m pip install .
      - name: Create local changes
        id: update
        run: |
          python -m oquat.large_scale_analysis -f
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --all -m "🦘 Re-run analysis"
